Main_Project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mainsite/', include('mainsite.urls')),
    path('', include('pages.urls')),
    path('', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/login.html'), name='logout'),
    path('solar-data/', views.SolarDataListView.as_view(), name='solar_data_list'),
    # '/solar-data/' URL로 요청이 들어오면 SolarDataListView를 사용
    ]

pages/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.mainpage, name='mainpage'),
    path('battery/', views.battery),
    path('lamp/', views.lamp),
    path('data/', views.data),
    path('battery-data-json/', views.battery_data_json, name='battery_data_json'),
    path('open_file/<str:file_name>', views.open_file, name='open_file'),
    path('data/', views.data_view, name='data_view'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

class SolarData(models.Model):
    date = models.DateTimeField()
    ac_w = models.FloatField()
    curr_short_battery = models.FloatField()
    curr_long_battery = models.FloatField()
    projected_power_production = models.FloatField()
    season = models.IntegerField()
    predicted_power_consumption = models.FloatField()
    select_storage_battery = models.CharField(max_length=50)
    select_supply_battery = models.CharField(max_length=50)
    light_control = models.IntegerField()

    def __str__(self):
        return f"{self.date} - {self.ac_w}W"

accounts/views.py
from django.views.generic import ListView
from .models import SolarData


class SolarDataListView(ListView):
    model = SolarData
    template_name = 'accounts/solar_data_list.html'
    context_object_name = 'solar_data_list'

templates/accounts/login.html
<!DOCTYPE html>
{% load static %}

<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>login - SolarEMS</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    </head>
    <body class="login_form">
        <div class="login-container">
            <div class="login-box">
                <h2>로그인</h2>
                {% if form.errors %}
                <p class="error-message">비밀번호가 틀립니다. 다시 시도해주세요.</p>
                {% endif %}

                <form method="post" action="{% url 'accounts:login' %}">
                    {% csrf_token %}
                    <div class="input-group">
                        {{ form.username.label_tag }}
                        {{ form.username }}
                    </div>

                    <div class="input-group">
                        {{ form.password.label_tag }}
                        {{ form.password }}
                    </div>

                    <button type="submit" class="btn-login">로그인</button>
                </form>
            </div>
        </div>

    </body>
</html>